-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Instructor"
(
    instructor_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    last_name character varying(60) NOT NULL,
    first_name character varying(60) NOT NULL,
    email character varying(120) NOT NULL,
    department character varying(80) NOT NULL,
    PRIMARY KEY (instructor_id),
    CONSTRAINT uq_instructor_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Student"
(
    student_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    last_name character varying(60) NOT NULL,
    first_name character varying(60) NOT NULL,
    email character varying(120) NOT NULL,
    group_code character varying(20) NOT NULL,
    PRIMARY KEY (student_id),
    CONSTRAINT uq_student_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Course"
(
    course_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    title character varying(120) NOT NULL,
    credits smallint NOT NULL,
    semester smallint NOT NULL,
    PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public."Enrollment"
(
    course_id integer NOT NULL,
    student_id integer NOT NULL,
    instructor_id integer NOT NULL,
    grade smallint NOT NULL,
    attempt_no smallint NOT NULL,
    exam_date date NOT NULL,
    PRIMARY KEY (student_id, course_id, attempt_no, instructor_id)
);

CREATE TABLE IF NOT EXISTS public."CourseInstructor"
(
    course_id integer NOT NULL,
    instructor_id integer NOT NULL,
    PRIMARY KEY (course_id, instructor_id)
);

ALTER TABLE IF EXISTS public."Enrollment"
    ADD CONSTRAINT fk_enroll_student FOREIGN KEY (student_id)
    REFERENCES public."Student" (student_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Enrollment"
    ADD CONSTRAINT fk_enroll_course FOREIGN KEY (course_id)
    REFERENCES public."Course" (course_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Enrollment"
    ADD CONSTRAINT fk_enroll_course_instructor FOREIGN KEY (course_id, instructor_id)
    REFERENCES public."CourseInstructor" (course_id, instructor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."CourseInstructor"
    ADD CONSTRAINT "CourseInstructor.course_id" FOREIGN KEY (course_id)
    REFERENCES public."Course" (course_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."CourseInstructor"
    ADD CONSTRAINT "CourseInstructor.instructor_id" FOREIGN KEY (instructor_id)
    REFERENCES public."Instructor" (instructor_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;