-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.


BEGIN;

-- ===== Tables ===============================================================

CREATE TABLE IF NOT EXISTS public."Instructor"
(
    instructor_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    last_name      varchar(60)  NOT NULL,
    first_name     varchar(60)  NOT NULL,
    email          varchar(120) NOT NULL,
    department     varchar(80)  NOT NULL,
    CONSTRAINT pk_instructor PRIMARY KEY (instructor_id),
    CONSTRAINT uq_instructor_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Student"
(
    student_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    last_name   varchar(60)  NOT NULL,
    first_name  varchar(60)  NOT NULL,
    email       varchar(120) NOT NULL,
    group_code  varchar(20)  NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (student_id),
    CONSTRAINT uq_student_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Course"
(
    course_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    title     varchar(120) NOT NULL,
    credits   smallint     NOT NULL,
    semester  smallint     NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (course_id),

    -- CHECK constraints
    CONSTRAINT chk_course_credits_range CHECK (credits  >= 1 AND credits  <= 10),
    CONSTRAINT chk_course_semester_range CHECK (semester >= 1 AND semester <= 12)
);

CREATE TABLE IF NOT EXISTS public."Enrollment"
(
    course_id     integer NOT NULL,
    student_id    integer NOT NULL,
    instructor_id integer NOT NULL,
    CONSTRAINT pk_enrollment PRIMARY KEY (course_id, student_id, instructor_id)
);

CREATE TABLE IF NOT EXISTS public."Exam"
(
    student_id    integer NOT NULL,
    course_id     integer NOT NULL,
    instructor_id integer NOT NULL,
    attempt_no    smallint NOT NULL,
    document      varchar(255) NOT NULL,
    exam_date     date        NOT NULL,
    grade         smallint    NOT NULL,
    CONSTRAINT pk_exam PRIMARY KEY (student_id, course_id, instructor_id, attempt_no),

    -- CHECK constraints
    CONSTRAINT chk_exam_grade_range   CHECK (grade >= 0 AND grade <= 100),
    CONSTRAINT chk_exam_attempt_nonneg CHECK (attempt_no >= 1)
);

-- ===== FKs & Cascades =======================================================

ALTER TABLE IF EXISTS public."Enrollment"
  ADD CONSTRAINT fk_enroll_student
  FOREIGN KEY (student_id)    REFERENCES public."Student"(student_id)
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."Enrollment"
  ADD CONSTRAINT fk_enroll_course
  FOREIGN KEY (course_id)     REFERENCES public."Course"(course_id)
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."Enrollment"
  ADD CONSTRAINT fk_enroll_instructor
  FOREIGN KEY (instructor_id) REFERENCES public."Instructor"(instructor_id)
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."Exam"
  ADD CONSTRAINT fk_exam_stud_inst_cur
  FOREIGN KEY (course_id, student_id, instructor_id)
  REFERENCES public."Enrollment"(course_id, student_id, instructor_id)
  ON UPDATE CASCADE ON DELETE CASCADE;


END;
